### ISSUE TITLE
Feature request: Add reads de-duplication step before assembly

### ISSUE THREAD

**Issue by Michaelijesse** [fmalmeida/bacannot#104]
```console
ERROR ~ Error executing process > 'BACANNOT:FLYE (SRR5637694_subreads)'

Caused by:
  Process `BACANNOT:FLYE (SRR5637694_subreads)` terminated with an error exit status (1)

Command executed:

  # Save flye version
  flye -v > flye_version.txt ;

  # Run flye
  flye \
    --pacbio-raw \
    SRR5637694_subreads.fastq.gz \
    --out-dir flye_SRR5637694_subreads \
    --threads 8 &> flye.log ;

  # Save a copy for annotation
  cp flye_SRR5637694_subreads/assembly.fasta flye_SRR5637694_subreads.fasta

Command exit status:
  1

Command output:
  (empty)

Work dir:
  /home/centos/Michael/Bacannot/work/df/3a7e2a7d655c71e4e4abcbac5d1704

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

**Comment by fmalmeida** [comment]
Hello hello,

Can you check and share what is the content of the file called ‘flye.log’ inside this work dir?

With only this we cannot understand what caused the problem.

**Comment by fmalmeida** [comment]
Hi @Michaelijesse ,
Thanks for sharing. Good to know that it is not a bug in the pipeline. Thus I recommend the folllowing:

* That in order to use the pipeline for now, you manually run a de-duplication step in your reads so you can analyse them.

In the mean time, I will modify the name of this ticket and add it as a feature request for adding such step in the pipeline.

Once again, thanks for sharing.

**Comment by Michaelijesse** [comment]
Hi @fmalmeida Thank you for helping out. I will do accordingly..

**Comment by Michaelijesse** [comment]
seqkit rename <fastq.gz> works fine.

**Comment by fmalmeida** [comment]
Perfect, will add this. Thanks!

**Comment by Michaelijesse** [comment]
![image](https://github.com/fmalmeida/bacannot/assets/111333701/d8501938-1559-46ca-a3b5-a9d4fca80391)

I close this issue.

**Comment by Michaelijesse** [comment]
All solved!!
