### ISSUE TITLE
provide a small dataset for quick code tests

### ISSUE THREAD

**Issue by fmalmeida** [fmalmeida/bacannot#46]
Provide a small dataset to quickly check the code integrity.

The pipeline already has a test dataset that enables the checkup of the majority of processes with `-profile test`. However, it is not too small and it takes generally ~1-2h to finish.

So, when updating code, we generally want something quicker just to check its integrity. Therefore, it would be nice to have a super small dataset that enables this in less then 40 min.

Task:

- [x] provide a small dataset for quick testing the code integrity, while trying to execute most of processes
- [x] enable this with `-profile smaller-test`

**Comment by abhi18av** [comment]
Agreed, this would be super helpful even on Github CI/Actions tests.

**Comment by fmalmeida** [comment]
Found out that a run with _Haemophilus influenzae_ genome takes only 9 min to finish testing almost all modules, just not running the assembly modules neither the methylation calling module. But since the pipeline is properly compiled to run all the others successfully, it seems like a good dataset for quick testing the code integrity and also the modules executed.

Now, just needs to add this new test profile in `develop` and bring a new patch release.

**Comment by abhi18av** [comment]
This sounds great @fmalmeida  - do we have a tentative release date for the next release (or merge) ?

**Comment by fmalmeida** [comment]
Hi @abhi18av,

For the bigger release, which is related to issue #36 and the draft PR #44 I don't have yet a forecast, because I am not finding too much time to spent with these implementations now that the pipeline is stable. You can even see that the "remodelling" branch implemention (related to issue #36) is **super slow** and may take a good amount of time to be finished.

However, for the smallest changes, the ones that were addressed in the issues you've contributed and are already merged in the `develop` ... From my latest tests, I've seen that the branch seems to be already stable. I just want to test it two more times with a few datasets of mine before bringing it forward.

For these smaller ones, I think that a new release `3.0.1` could be published within the two next weeks.

😄

**Comment by abhi18av** [comment]
Ah, okay this makes sense Felipe, not a problem - time is limited resource 😉 

But thinking further about this, I think that maybe an `nf-core/modules` like approach for testing (pytest) might make more sense since we now have a smaller dataset.


This would ideally be done in conjunction with the possible refactoring of modules.


But no hurries, I think sometimes more than engineering, a pipeline (or product) needs more users to guide the overall development :)

**Comment by fmalmeida** [comment]
I don't know much about the pytest that nf-core executes in their pipelines/modules. But I think that it is worthy to learn anything that would make testing easier.

If you could point me out to such examples and how they are done or configured so I can try to learn more about them, it would be nice.

And no worry, every input is valuable, and I am pleased about the discussions and inputs you've brought to me 😄

**Comment by abhi18av** [comment]
> If you could point me out to such examples and how they are done or configured so I can try to learn more about them, it would be nice.

Sure, Felipe 👍 

Actually, I saw this practice initiated by the nf-core folks, this is documented in the talks here 

- https://youtu.be/xuNYATGFuw4 (contributing to nf-core/modules)
- https://www.youtube.com/watch?v=Wc4A2tQ6WWY (module code)
- https://www.youtube.com/watch?v=QXfAerydAT0 (module test data)


Beyond nf-core, an independent effort by Robert was done for bactopia https://github.com/bactopia/bactopia who relied on the data here https://github.com/bactopia/bactopia-tests 

However if you have other ideas in mind, I'd be happy to discuss and try it out with you :)

**Comment by fmalmeida** [comment]
Hi @abhi18av,

Many thanks for pointing out these sources. I will surely make some efforts to read and study them.

Having knowledge on how to speed-up and automatize tests will be awesome for this repository in specific and also for my future works.


Thank you.

😁😁
